PR request
AsadShakeel/veryfi-java pull request #5
Opened 2021-06-02 09:34 UTC by riyazah18

request method name changed to processRequest and logging enhancement.

2021-06-02 10:00 UTC, AsadShakeel requested changes

2021-06-02 10:00 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Getting Document with documentId["+documentId+"]");
We can use the logging formatting here like
`logger.info("Getting Document with documentId[{}]", documentId);`

2021-06-02 10:00 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Generating Signature -");
nit: `-` can be removed from logging

2021-06-02 10:00 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Processing Request -[s t a r t]");
We can include the method type and endpoint name in the logging for better understanding.
Also, the `httpVerb` can be refactored to `httpMethod`.

2021-06-02 10:00 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Processing Document -");
nit: extra `-`

2021-06-02 10:00 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Process Document -- filePath["+filePath+"],fileName["+fileName+"]");
logging formatting can be done here and below all logging statements as well.

2021-06-02 11:20 UTC, riyazah18 commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Getting Document with documentId["+documentId+"]");
done

2021-06-02 11:20 UTC, riyazah18 commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Generating Signature -");
done

2021-06-02 11:29 UTC, riyazah18 commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Processing Request -[s t a r t]");
done

2021-06-02 11:30 UTC, riyazah18 commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Processing Document -");
done

2021-06-02 11:47 UTC, AsadShakeel requested changes

2021-06-02 11:47 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Processing Request with httpMethod[{httpMethod}],endpointName[{}]-[s t a r t]",httpMethod,endpointName);
`httpMethod[{httpMethod}]`  should be replaced by `httpMethod[{}]`
nit: spacing with commas

2021-06-02 11:47 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Process Document with filePath[{}],fileName[{}]",filePath,fileName);
nit: spacing with commas

2021-06-02 11:47 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Process Document File -- filePath["+filePath+"],fileName["+fileName+"]");
nit: logging format and spacing issue

2021-06-02 11:47 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Deleting Document -- documentId["+documentId+"]");
same
nit: logging format and spacing issue

2021-06-02 11:47 UTC, AsadShakeel commented on src/main/java/com/veryfi/VeryfiClient.java
> +        logger.info("Updating Document -- documentId["+id+"]");
same
nit: logging format and spacing issue

2021-06-03 07:55 UTC, AsadShakeel approved these changes

2021-06-03 07:55 UTC, merged